# Generated by Django 4.0.1 on 2022-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='icons')),
            ],
        ),
    ]
