# Generated by Django 4.0.1 on 2022-01-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=100)),
                ('image_url', models.URLField(default='')),
            ],
        ),
    ]
