# Generated by Django 4.0.1 on 2022-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
