# Generated by Django 4.0.1 on 2022-01-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_rename_post_text_post_text_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default=False),
        ),
    ]
