# Generated by Django 4.0.1 on 2022-01-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0003_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
